# Generated by Django 3.2.4 on 2021-06-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follower'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('user', 'follower'), name='user_and_follower_unique'),
        ),
    ]
