# Generated by Django 3.2.4 on 2021-06-11 19:46

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follower_user_and_follower_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, upload_to=publications.models.get_filepath),
        ),
    ]
