# Generated by Django 3.2.4 on 2021-06-11 19:47

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to=publications.models.get_filepath),
        ),
    ]
