# Generated by Django 3.2.4 on 2021-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_like_user_and_publication_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='publications.Tag'),
        ),
    ]
