# Generated by Django 3.2.4 on 2021-06-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20210605_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-created_at',), 'verbose_name': 'publicação', 'verbose_name_plural': 'publicações'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='publication',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
