# Generated by Django 3.2.4 on 2021-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20210606_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
