# Generated by Django 3.2.4 on 2021-06-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_alter_publication_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(default=None, to='publications.Tag'),
        ),
    ]
