# Generated by Django 3.2.4 on 2021-06-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_alter_publication_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='publications.Tag'),
        ),
    ]
