# Generated by Django 3.2.4 on 2021-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_alter_publication_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
