# Generated by Django 3.2.4 on 2021-06-13 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0021_auto_20210613_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='Saved',
        ),
    ]
