# Generated by Django 3.2.4 on 2021-06-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0022_rename_save_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ('-created_at',), 'verbose_name': 'salvo', 'verbose_name_plural': 'salvos'},
        ),
        migrations.AlterModelTable(
            name='saved',
            table='saved',
        ),
    ]
