# Generated by Django 3.2.4 on 2021-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_auto_20210613_1329'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='saved',
            constraint=models.UniqueConstraint(fields=('publication', 'user'), name='publication_and_user_uniq'),
        ),
    ]
